### ISSUE TITLE
Wox got an error

### ISSUE THREAD

**Issue by achiyae** [Wox-launcher/Wox#1427] opened 2017-05-20 18:29 UTC
Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.14393.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\...\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 05/20/2017 21:23:55
[2017-05-20.zip](https://github.com/Wox-launcher/Wox/files/1016403/2017-05-20.zip)

Exception:
mscorlib
System.ArgumentOutOfRangeException
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.ArrayList.set_Item(Int32 index, Object value)
   at System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   at System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by lances101** [comment] 2017-12-26 22:18
Duplicate of #1404
Please track this problem there.

**Closed as completed by lances101** 2017-12-26 22:18 UTC
