### ISSUE TITLE
My application has stopped working suddenly!

### ISSUE THREAD

**Issue by victorsnk** [Wox-launcher/Wox#1600] opened 2017-09-17 09:59 UTC
My application has stopped working. Reinstall it and it does not solve the problem either. Start the app but do not search or find anything. Example here: https://ibb.co/fmHizQ

Thanks!!

**Comment by arthur-st** [comment] 2017-09-25 09:27
Same problem. Wox 1.3.424 on Windows 10 (x64). Worked fine yesterday, no Windows update or anything similar overnight, as far as I know, so not sure what changed. 

Startup log: https://gist.github.com/arthur-st/4275e0918c671db68596df0923353d0a

**Comment by Gamerbiomek2** [comment] 2017-09-26 06:34
Same problem. Wox 1.3.424 on Windows 10 (x64)
Wox worked before I updated

**Comment by lances101** [comment] 2017-12-22 22:19
Based on @arthur-st's log it seems like a duplicate of #1394
@victorsnk Could you add more information about the issue? Please attach a log that contains the error. 
You can find it in `%appdata%\Wox\Logs\<version_folder>\<date>.txt`

**Comment by bao-qian** [comment] 2020-04-25 08:45
Need more info.
You can also try new build https://github.com/Wox-launcher/Wox/releases
If problem still exist, try reset by delete `%APPDATA%Wox` directory.
Open new issue once you got more info and above method won't help.

**Closed as completed by bao-qian** 2020-04-25 08:45 UTC
