### ISSUE TITLE
Error on Startup System.IO.IOException

### ISSUE THREAD

**Issue by mjichael** [Wox-launcher/Wox#1524] opened 2017-07-25 20:57 UTC
[2017-07-26.txt](https://github.com/Wox-launcher/Wox/files/1174751/2017-07-26.txt)

Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.15063.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: 
Date: 07/26/2017 06:53:16
Exception:
mscorlib
System.IO.IOException
The process cannot access the file 'C:\Users\mikej\AppData\Roaming\Wox\Cache\Image.cache' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Wox.Infrastructure.Storage.BinaryStorage`1.Save(T data) in C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:line 99
   at Wox.Infrastructure.Storage.BinaryStorage`1.TryLoad(T defaultData) in C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:line 44
   at Wox.Infrastructure.Image.ImageLoader.Initialize() in C:\projects\wox\Wox.Infrastructure\Image\ImageLoader.cs:line 37
   at Wox.App.<OnStartup>b__10_0() in C:\projects\wox\Wox\App.xaml.cs:line 52
   at Wox.Infrastructure.Stopwatch.Normal(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 31
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by lances101** [comment] 2017-12-20 12:46
Duplicate of #1394 

You can keep track of the problem in the mentioned issue.

**Closed as completed by lances101** 2017-12-20 12:46 UTC
