### ISSUE TITLE
Wox cannot center itself when a DisplayPort monitor disconnects and reconnects

### ISSUE THREAD

**Issue by be5invis** [Wox-launcher/Wox#227] opened 2015-01-02 10:41 UTC
![image](http://ww1.sinaimg.cn/large/798f7769gw1envd0ccv5cj21kw0w0gry.jpg)

**Comment by qianlifeng** [comment] 2015-01-06 15:34
Currently, Wox remembered the exact pixels of the last location. Maybe we can add an option to let wox show in the center of the screen, Or remember the percentage of the screen instead of the pixels.

**Comment by orzFly** [comment] 2015-01-06 16:17
@qianlifeng It already uses percentage instead of the pixels at this moment. The problem is when the external monitor disconnects, the current location of the main window is undefined thus `origScreen` is undefined too.
https://github.com/qianlifeng/Wox/blob/master/Wox/MainWindow.xaml.cs#L436

**Comment by be5invis** [comment] 2015-01-06 21:49
@orzFly Currently i am using a single Dell P2715Q monitor which when it enters power-saving mode, it "disconnects" itself.

**Comment by JayXon** [comment] 2015-01-13 03:56
![wox](https://cloud.githubusercontent.com/assets/1552641/5715805/bbde9970-9aad-11e4-95ea-e478a02e0fee.png)
It seems my situation is a little different.

**Comment by be5invis** [comment] 2015-02-05 17:43
@JayXon 收藏夹不错，求 xml
看到 ustc，校友？

**Comment by JayXon** [comment] 2015-02-05 18:19
@be5invis 嗯我是09004的，收藏夹很久没整理了，好多死链，就不分享了吧

**Comment by qianlifeng** [comment] 2015-02-17 11:15
I'm closing this becaue it will be fixed by adding an option for centering Wox. Tracked in #251

**Closed as completed by qianlifeng** 2015-02-17 11:15 UTC
