### ISSUE TITLE
Wox Crashed

### ISSUE THREAD

**Issue by Moyf** [Wox-launcher/Wox#1621] opened 2017-10-10 12:27 UTC
## English

Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.15063.0
IntPtr Length: 8
x64: True

Python Path: pythonw.exe
Everything SDK Path: C:\Users\hln4446\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 10/10/2017 20:24:11
Exception:
mscorlib
System.ArgumentOutOfRangeException
插入索引已超出范围。必须为非负值，并且必须小于或等于大小。
参数名: index
   在 System.Collections.ArrayList.Insert(Int32 index, Object value)
   在 System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   在 System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   在 System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   在 MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2017-10-10.txt](https://github.com/Wox-launcher/Wox/files/1371829/2017-10-10.txt)

**Comment by lances101** [comment] 2017-12-26 22:19
Duplicate of #1404 
Please track this problem there.

**Closed as completed by lances101** 2017-12-26 22:19 UTC
