### ISSUE TITLE
System.ArgumentOutOfRangeException: Insertion index was out of range. Must be non-negative and less than or equal to size.

### ISSUE THREAD

**Issue by ShiftSix** [Wox-launcher/Wox#1815] opened 2018-01-09 06:07 UTC
Wox version: 1.3.475
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\lian.liu\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 01/09/2018 14:05:08
Exception:
System.ArgumentOutOfRangeException: Insertion index was out of range. Must be non-negative and less than or equal to size.
Parameter name: index
   at System.Collections.ArrayList.Insert(Int32 index, Object value)
   at System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   at System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2018-01-09.txt](https://github.com/Wox-launcher/Wox/files/1614051/2018-01-09.txt)

**Comment by lances101** [comment] 2018-01-11 18:27
Duplicate of https://github.com/Wox-launcher/Wox/issues/926

**Closed as completed by lances101** 2018-01-11 18:27 UTC
