### ISSUE TITLE
Feature Request: Hide Wox Icon in Taskbar

### ISSUE THREAD

**Issue by ghost** [Wox-launcher/Wox#1483] opened 2017-06-19 13:48 UTC
An option to fully hide the icon from the taskbar would be a nice addition

**Comment by iHandle** [comment] 2017-06-24 07:43
Are you using windows10?  You can just drag the icon to the hidden area of the taskbar.

**Comment by lances101** [comment] 2017-12-22 21:29
Duplicate of #563

**Closed as completed by lances101** 2017-12-22 21:29 UTC
