### ISSUE TITLE
Maybe round borders?

### ISSUE THREAD

**Issue by joaopedrosgs** [Wox-launcher/Wox#1749] opened 2017-12-13 12:38 UTC
There is a way to add rounded borders to Wox? (like albert or alfred)

**Comment by lances101** [comment] 2017-12-20 13:47
Duplicate of https://github.com/Wox-launcher/Wox/issues/208

You can get an example of a rounded theme with shadows here:
https://gist.github.com/lances101/ed863ae9924284bd8cfa

**Closed as completed by lances101** 2017-12-20 13:47 UTC
