### ISSUE TITLE
wox crash on win10 1709

### ISSUE THREAD

**Issue by lonardo** [Wox-launcher/Wox#1692] opened 2017-11-17 01:33 UTC
Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.16299.0
IntPtr Length: 8
x64: True

Python Path: D:\Python27\pythonw.exe
Everything SDK Path: C:\Users\wangningbo\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 11/17/2017 09:30:08
Exception:
Squirrel
System.Exception
Couldn't acquire lock, is another instance running
   在 Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut) 位置 C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\Utility.cs:行号 778
   在 Squirrel.UpdateManager.<acquireUpdateLock>b__32_0() 位置 C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:行号 274
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext() 位置 C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:行号 56
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Wox.Core.Updater.<UpdateApp>d__1.MoveNext() 位置 C:\projects\wox\Wox.Core\Updater.cs:行号 41
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Wox.SettingWindow.<OnCheckUpdates>d__24.MoveNext() 位置 C:\projects\wox\Wox\SettingWindow.xaml.cs:行号 309
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2017-11-17.txt](https://github.com/Wox-launcher/Wox/files/1480793/2017-11-17.txt)
[2017-11-02.txt](https://github.com/Wox-launcher/Wox/files/1480795/2017-11-02.txt)
[2017-11-03.txt](https://github.com/Wox-launcher/Wox/files/1480796/2017-11-03.txt)
[2017-11-06.txt](https://github.com/Wox-launcher/Wox/files/1480797/2017-11-06.txt)
[2017-11-07.txt](https://github.com/Wox-launcher/Wox/files/1480799/2017-11-07.txt)
[2017-11-08.txt](https://github.com/Wox-launcher/Wox/files/1480800/2017-11-08.txt)
[2017-11-09.txt](https://github.com/Wox-launcher/Wox/files/1480801/2017-11-09.txt)
[2017-11-10.txt](https://github.com/Wox-launcher/Wox/files/1480802/2017-11-10.txt)
[2017-11-13.txt](https://github.com/Wox-launcher/Wox/files/1480803/2017-11-13.txt)
[2017-11-14.txt](https://github.com/Wox-launcher/Wox/files/1480804/2017-11-14.txt)
[2017-11-15.txt](https://github.com/Wox-launcher/Wox/files/1480805/2017-11-15.txt)
[2017-11-16.txt](https://github.com/Wox-launcher/Wox/files/1480806/2017-11-16.txt)

**Comment by lances101** [comment] 2017-12-20 14:16
Duplicate of #1396

**Closed as completed by lances101** 2017-12-20 14:16 UTC
