### ISSUE TITLE
Wox got an error.

### ISSUE THREAD

**Issue by nereuseng** [Wox-launcher/Wox#1769] opened 2017-12-21 00:29 UTC
Updated: Delete the Image.cache file make Wox working again.

***********************************************

Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.16299.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: 
Date: 12/21/2017 08:24:38
Exception:
mscorlib
System.IO.IOException
由於另一個處理序正在使用檔案 'C:\Users\nereu\AppData\Roaming\Wox\Cache\Image.cache'，所以無法存取該檔案。
   於 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   於 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   於 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   於 System.IO.FileStream..ctor(String path, FileMode mode)
   於 Wox.Infrastructure.Storage.BinaryStorage`1.Save(T data) 於 C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs: 行 99
   於 Wox.Infrastructure.Storage.BinaryStorage`1.TryLoad(T defaultData) 於 C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs: 行 44
   於 Wox.Infrastructure.Image.ImageLoader.Initialize() 於 C:\projects\wox\Wox.Infrastructure\Image\ImageLoader.cs: 行 37
   於 Wox.App.<OnStartup>b__10_0() 於 C:\projects\wox\Wox\App.xaml.cs: 行 52
   於 Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 於 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs: 行 31
   於 System.Windows.Application.OnStartup(StartupEventArgs e)

[2017-12-21.txt](https://github.com/Wox-launcher/Wox/files/1577460/2017-12-21.txt)

**Comment by lances101** [comment] 2017-12-22 16:04
Duplicate of #1394

**Closed as completed by lances101** 2017-12-22 16:04 UTC
