### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by LoZeno** [Wox-launcher/Wox#2702] opened 2020-01-17 10:27 UTC
### Are you submitting a bug report?
No

The [last release](https://github.com/Wox-launcher/Wox/releases/tag/v1.3.578) dates back to 22 December 2018, and since then there's been quite a few improvements to the code; can we finally have a new Release, so that package managers like Scoop and Chocolatey can pick it up?

**Comment by jjw24** [comment] 2020-01-18 01:44
Hey how's it going. Most of the open PRs have been added to my branch. Feel free to use this one in the mean time:
https://github.com/jjw24/Wox/releases

**Comment by BlueDrink9** [comment] 2020-01-18 03:38
Are there any active contributors? A new release really would be swell

**Comment by LoZeno** [comment] 2020-01-18 09:43
> 
> 
> Hey how's it going. Most of the open PRs have been added to my branch. Feel free to use this one in the mean time:
> https://github.com/jjw24/Wox/releases

Thanks, that is something useful. But the reason for a new release is to allow package managers to pick up updates and allow those who installed wox through said package managers to get the latest version, since the code has been updated several times (plus the PRs you merged in your fork).

@jjw24  Have you considered putting your own fork up into chocolatey or scoop?

**Comment by jjw24** [comment] 2020-01-18 09:54
>Have you considered putting your own fork up into chocolatey or scoop?

At the moment my fork is working on Wox's auto updates. Choco maybe something later but not considered at this stage. I understand your request because I use the package manager extensively.

**Comment by vivadavid** [comment] 2020-02-05 00:29
Hi, @jjw24 !

I'd like to know if your fork is like a beta channel (where features and fixes are tested) or if, instead, it's the programme we need to download and use from now on because the original Wox is dead.

I've just got version 1.3.524+JJW24.v1.39.19, but I'm a bit confused about the terminology although I understand it's based on 1.3.524. My confusion is increased by the fact that, on the portable version, there are two subfolders, one of which corresponds to version 1.2.0. On top of that, file Wox.exe appears three times.

There's one more thing I don't understand. I thought "Query search precision" was a new feature, but it's only available when I click on the Wox.exe found on the <app-1.2.0> subfolder.

I just love Wox and I'd like to know how to proceed in the future.

Thanks!

**Comment by jjw24** [comment] 2020-02-05 01:54
> Hi, @jjw24 !
> 
> I'd like to know if your fork is like a beta channel (where features and fixes are tested) or if, instead, it's the programme we need to download and use from now on because the original Wox is dead.

Hi @vivadavid, my fork is not a beta channel for Wox. It started with me adding some features and fixes and submitting them back to upstream for everyone else to use. However seeing this upstream repo's development has ceased for over a year, and a couple contributors and myself continued to update Wox, I would say now my fork is continuing the development of Wox until upstream becomes active again.


> I've just got version 1.3.524+JJW24.v1.39.19, but I'm a bit confused about the terminology although I understand it's based on 1.3.524. My confusion is increased by the fact that, on the portable version, there are two subfolders, one of which corresponds to version 1.2.0. On top of that, file Wox.exe appears three times.

Use the exe on the top level, Wox\Wox.exe, don't worry about the one in 'app 1.2.0' folder (although both should work the same). Not sure why there are duplicates, seems to be like this since the original 524 version.

> There's one more thing I don't understand. I thought "Query search precision" was a new feature, but it's only available when I click on the Wox.exe found on the <app-1.2.0> subfolder.

For me it appear regardless which exe I run. Did you extract the portable version to its own location (not to the original 524 location if you have it installed)?

> I just love Wox and I'd like to know how to proceed in the future.
> 
> Thanks!

You can use my fork's as it will continue to get refinements.

**Comment by BlueDrink9** [comment] 2020-02-05 02:08
Do you know why upstream isn't merging your changes? I see the maintainer is at least peripherally active

**Comment by jjw24** [comment] 2020-02-05 02:16
> Do you know why upstream isn't merging your changes? I see the maintainer is at least peripherally active

Not sure, have not gotten in touch with the maintainer, but usually it's a combination of things including time commitment, code base complications and PR reviews also take a lot of time especially if they are complex changes.

**Comment by vivadavid** [comment] 2020-02-05 12:39
Hi, @jjw24 !

Thank you for your reply! When I unzipped the portable version of your fork, I had previously formatted my PC, so there was no previous installation.

The first time I ran the Wox.exe located on the top level folder, it actually ran version 1.2, but I've just tried again and it's running 1.3.524, so I'm not sure what's happening here. Maybe the first time I ran the programme, I did run the Wox.exe in the <app-1.2.0> folder. In any case, I should just use the installer and forget about the portable version.

What I can confirm is that version 1.3.524 doesn't show the "Query search precision" feature, but if I close the programme and I specifically run the Wox.exe located in the <app-1.2.0> folder, the feature is there.

From now on, I'll use your fork and I'll stick to the installer.

Thank you for work improving Wox!

**Comment by LoZeno** [comment] 2020-03-03 09:51
Pinging @bao-qian to see this since he seems to be active again

**Comment by bao-qian** [comment] 2020-05-14 19:05
Hi guys,

https://github.com/Wox-launcher/Wox/releases

thanks for support and sorry for long, and sorry for making you wait so long. 
this project is back to active development, with more than 300 commit and more than 5 release in a month. all old pr has been merged as well.

![image](https://user-images.githubusercontent.com/1169912/81972789-b61d9500-9655-11ea-8f2e-ecbf53ab57df.png)

@LoZeno 
@BlueDrink9 
@vivadavid

**Closed as completed by bao-qian** 2020-05-14 19:05 UTC

**Comment by LoZeno** [comment] 2020-05-14 19:19
@bao-qian Just an FYI: some package managers (like [scoop](https://github.com/lukesampson/scoop)) only pick up new releases from GitHub if they are marked as "Release", not "pre-release".

As such, none of the pre-releases you published so far have appeared for scoop users

**Comment by bao-qian** [comment] 2020-05-14 19:29
@LoZeno 
thanks, will mark it as release after collect some user feedback.

**Comment by BlueDrink9** [comment] 2020-05-14 20:18
Thank you for your work!

**Comment by LoZeno** [comment] 2020-05-18 08:05
@bao-qian also noticed that even the users of [chocolatey](https://chocolatey.org/packages/wox#upgrade) won't see any new update to Wox since they are all marked as pre-release. Most package managers only make full releases available as pre-releases are considered beta and not suitable for most users.

**Comment by bao-qian** [comment] 2020-05-18 08:08
@LoZeno 
thanks for info, I'm doing some final testing , will release stable version tomorrow or the after tomorrow.

**Comment by jamesdoran** [comment] 2021-03-17 21:12
> @LoZeno
> thanks for info, I'm doing some final testing , will release stable version tomorrow or the after tomorrow.

@bao-qian, looks like this was released as 'pre-release' in May last year. When do you plan to do a stable release please?
