### ISSUE TITLE
bug：json库的引用丢失，找不到dll

### ISSUE THREAD

**Issue by ilharp** [Wox-launcher/Wox#1910] opened 2018-02-22 03:05 UTC
### Are you submitting a bug report?

(write your answer here)

yes. 

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

对不起，这bug一开机就有了，你叫我复现？截图？不存在的……话说这个版本bug超级多啊……还有你是直接拿debug做了release发布了？
而且这引用这……不是我的锅啊……

Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\afany\AppData\Roaming\Wox\Logs\1.3.475\2018-02-22.txt
2. copy below exception message

Wox version: 1.3.475
OS Version: Microsoft Windows NT 10.0.17604.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: 
Date: 02/22/2018 10:58:08
Exception:
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
   at Wox.Plugin.Express.Main.Init(PluginInitContext context)
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 19
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 101
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Wox.Core.Plugin.PluginManager.InitializePlugins(IPublicAPI api) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 91
   at Wox.App.<OnStartup>b__10_0() in C:\projects\wox\Wox\App.xaml.cs:line 60
   at Wox.Infrastructure.Stopwatch.Normal(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 31
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---> (Inner Exception #0) System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at Wox.Plugin.Express.Main.Init(PluginInitContext context)
   at Wox.Infrastructure.Stopwatch.Debug(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 19
   at Wox.Core.Plugin.PluginManager.<>c.<InitializePlugins>b__19_0(PluginPair pair) in C:\projects\wox\Wox.Core\Plugin\PluginManager.cs:line 101
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
<---

**Comment by jhdxr** [comment] 2018-02-22 05:05
仔细看log的话，这个是由于插件`Wox.Plugin.Express`导致的崩溃。可以先暂时禁用（移除插件的目录）。

如果有其他bug可以单开issue

Duplicate of #1841

**Closed as completed by jhdxr** 2018-02-22 05:05 UTC
