### ISSUE TITLE
ERROR-Wox version: 1.3.475

### ISSUE THREAD

**Issue by cyddgh** [Wox-launcher/Wox#1856] opened 2018-01-23 14:31 UTC
### Are you submitting a bug report?

(write your answer here)

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

(paste here)
Wox version: 1.3.475
OS Version: Microsoft Windows NT 10.0.16299.0
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: C:\Users\Chen Yongda\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 01/23/2018 22:24:20
Exception:
System.InvalidOperationException: 只能在按下主鼠标按钮时调用 DragMove。
   在 System.Windows.Window.DragMove()
   在 Wox.MainWindow.OnMouseDown(Object sender, MouseButtonEventArgs e) 位置 C:\projects\wox\Wox\MainWindow.xaml.cs:行号 151
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Detailed logs

(drop your log file here)
[2018-01-23.txt](https://github.com/Wox-launcher/Wox/files/1656294/2018-01-23.txt)

**Comment by lances101** [comment] 2018-02-09 21:32
Duplicate of https://github.com/Wox-launcher/Wox/issues/811

**Closed as completed by lances101** 2018-02-09 21:32 UTC
