### ISSUE TITLE
Feature request: Do not change selection on mousemove/hover

### ISSUE THREAD

**Issue by puco** [Wox-launcher/Wox#1395] opened 2017-04-26 09:47 UTC
As I interact with Wox mostly via keyboard, whenever I move a mouse pointer (accidentally) over the wox window it can happen that the selection changes. This is quite distracting and would be nice if it could be disabled.

**Comment by jhdxr** [comment] 2017-04-28 03:58
duplicate of #1193

**Closed as completed** 2017-12-26 23:19 UTC
