### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by Cr321** [Wox-launcher/Wox#1676] opened 2017-11-07 04:38 UTC
Wox version: 1.3.183
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 11/07/2017 12:35:36
Exception:
Squirrel
System.Exception
Couldn't acquire lock, is another instance running
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut) in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:line 737
   at Squirrel.UpdateManager.<acquireUpdateLock>b__1e() in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:line 248
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__0.MoveNext() in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__50`1.MoveNext() in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:line 535
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Squirrel.EasyModeMixin.<UpdateApp>d__11.MoveNext() in c:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\IUpdateManager.cs:line 172
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wox.Core.Updater.<UpdateApp>d__0.MoveNext() in C:\projects\wox\Wox.Core\Updater.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by lances101** [comment] 2017-12-20 14:15
Duplicate of #1396

**Closed as completed by lances101** 2017-12-20 14:15 UTC
