### ISSUE TITLE
Issue found 2017-12-07

### ISSUE THREAD

**Issue by tmwatchanan** [Wox-launcher/Wox#1725] opened 2017-12-07 16:08 UTC
[2017-12-07.txt](https://github.com/Wox-launcher/Wox/files/1539756/2017-12-07.txt)

Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.16299.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\Watchanan\Anaconda3\pythonw.exe
Everything SDK Path: C:\Users\Watchanan\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 12/07/2017 23:05:33
Exception:
mscorlib
System.ArgumentOutOfRangeException
Insertion index was out of range. Must be non-negative and less than or equal to size.
Parameter name: index
   at System.Collections.ArrayList.Insert(Int32 index, Object value)
   at System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   at System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by lances101** [comment] 2017-12-22 20:07
Thank you for attaching the log file, but I need for information to figure out what happened.
What were you trying to do when the error happened?

**Comment by lances101** [comment] 2017-12-26 22:19
This is a duplicate of #1404 
Please track this problem there.

**Closed as completed by lances101** 2017-12-26 22:19 UTC
