### ISSUE TITLE
Wox-1.3.424 got an error

### ISSUE THREAD

**Issue by lcm2179** [Wox-launcher/Wox#1561] opened 2017-08-17 01:58 UTC
Wox version: 1.3.424
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
IntPtr Length: 8
x64: True

Python Path: 
Everything SDK Path: 
Date: 08/17/2017 09:37:39
Exception:
mscorlib
System.IO.IOException
The process cannot access the file 'C:\Users\dell\AppData\Roaming\Wox\Cache\Image.cache' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Wox.Infrastructure.Storage.BinaryStorage`1.Save(T data) in C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:line 99
   at Wox.Infrastructure.Storage.BinaryStorage`1.TryLoad(T defaultData) in C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:line 44
   at Wox.Infrastructure.Image.ImageLoader.Initialize() in C:\projects\wox\Wox.Infrastructure\Image\ImageLoader.cs:line 37
   at Wox.App.<OnStartup>b__10_0() in C:\projects\wox\Wox\App.xaml.cs:line 52
   at Wox.Infrastructure.Stopwatch.Normal(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 31
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2017-08-17.txt](https://github.com/Wox-launcher/Wox/files/1229929/2017-08-17.txt)
[2017-08-17.txt](https://github.com/Wox-launcher/Wox/files/1229932/2017-08-17.txt)

**Comment by lances101** [comment] 2017-12-20 12:48
Duplicate of #1394 

You can keep track of the problem in the mentioned issue.

**Closed as completed by lances101** 2017-12-20 12:48 UTC
