### ISSUE TITLE
数字达到11位以后，计算器插件出错

### ISSUE THREAD

**Issue by edsion1107** [Wox-launcher/Wox#1664] opened 2017-11-03 06:38 UTC
1509683404004-1509683392773=0
![tim 20171103143706](https://user-images.githubusercontent.com/1925286/32362470-921e0966-c0a4-11e7-88f8-01ef1f14263c.png)

**Comment by edsion1107** [comment] 2017-11-03 06:38
版本1.3.183

**Comment by jhdxr** [comment] 2017-11-03 06:40
duplicate of #1022 

用最新的：https://ci.appveyor.com/project/happlebao/wox/build/artifacts

**Closed as completed by jhdxr** 2017-11-03 06:40 UTC
