### ISSUE TITLE
Font settings won't work in themes other than default theme

### ISSUE THREAD

**Issue by mgrddsj** [Wox-launcher/Wox#2118] opened 2018-07-18 09:13 UTC
### Are you submitting a bug report?

Yes

### Steps to reproduce

1. Switch to "Dark" theme in Wox
2. Change the font below (I chose "Comic Sans MS"), it will not make any effect. 
3. Switch back to default theme then switch back to "Dark" theme, the font works. 
4. Restart Wox, the font changes to default again. Need to repeat the steps above to use Dark theme and the font together. 

### Wox Error Window text

(Doesn't have an error window. Just not functioning correctly.) 

### Detailed logs

Doesn't have log file. 

### Screenshots (optional)
Steps to reproduce by gif:

![wox](https://user-images.githubusercontent.com/36990144/42871645-70899c56-8aad-11e8-85ae-27f20e5a621f.gif)

**Comment by proimage** [comment] 2019-01-27 18:41
I'm getting this as well. Any news?

**Comment by Oaklight** [comment] 2019-07-08 19:52
This can be fixed by first setting the font, then switching to another theme (the font is active at this point) and switching back.
I suspect the problem is caused by the font loading only happens during or after a theme is loaded.

**Comment by bao-qian** [comment] 2020-05-26 06:33
Please try new release with tons of bug fix and 100 times speedup.
https://github.com/Wox-launcher/Wox/releases

If problem still exist, try reset by delete %APPDATA%Wox directory.
Reopen if above method won't help.

**Closed as completed by bao-qian** 2020-05-26 06:33 UTC
