### ISSUE TITLE
How to filter out some files from Wox

### ISSUE THREAD

**Issue by andrecarlucci** [Wox-launcher/Wox#1854] opened 2018-01-22 12:05 UTC
Hi guys,

How to filter out some files using patterns? 
For instance, I would like to remove "*uninstall*.*" from Wox when searching for a program to open.
Tks!

**Comment by lances101** [comment] 2018-02-01 13:37
Duplicate of #239. Comment there for discussion and updates. 
PR covering this exists #800. Still not merged due to the PR being unmergeable at this point.

**Closed as completed by lances101** 2018-02-01 13:37 UTC
