### ISSUE TITLE
IOException

### ISSUE THREAD

**Issue by Michellexmz** [Wox-launcher/Wox#1461] opened 2017-06-12 00:19 UTC
## Known problems for 1.3.183:

1. `System.NullReferenceException`: https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424
2. `System.UriFormatException`: delete your old theme file
3. `System.Threading.Tasks.TaskCanceledException`: https://github.com/Wox-launcher/Wox/releases/tag/v1.3.424

## English

Try search existing issues before you open new one

1. Wox version / commit number: 
2. Steps to **reproduce** the bug:
3. Windows version:
4. Exception:
5. **whole** log file （`%APPDATA%\Wox\Logs\version\date.txt`):
6. Screenshot (optional): 

## 中文 / Chinese

提问之前搜索一下已经有的 issue

1. Wox 版本 / commit number：1.3.424
2. 如何**重现** bug：
3. Windows 版本：Microsoft Windows NT 10.0.14393.0
4. Exception：
Python Path: 
Everything SDK Path: 
Date: 06/12/2017 08:13:26
Exception:
mscorlib
System.IO.IOException
文件“C:\Users\MichelleZhang\AppData\Roaming\Wox\Cache\Image.cache”正由另一进程使用，因此该进程无法访问此文件。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   在 System.IO.FileStream..ctor(String path, FileMode mode)
   在 Wox.Infrastructure.Storage.BinaryStorage`1.Save(T data) 位置 C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:行号 99
   在 Wox.Infrastructure.Storage.BinaryStorage`1.TryLoad(T defaultData) 位置 C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:行号 44
   在 Wox.Infrastructure.Image.ImageLoader.Initialize() 位置 C:\projects\wox\Wox.Infrastructure\Image\ImageLoader.cs:行号 37
   在 Wox.App.<OnStartup>b__10_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 52
   在 Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 31
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

5. **整个** log 文件 （`%APPDATA%\Wox\Logs\version\date.txt`）：
2017-06-12 00:25:41.0605|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2017-06-12 00:25:41.0759|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2017-06-12 00:25:41.0779|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.Net.WebException>
2017-06-12 00:25:41.0779|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <未能解析此远程名称: 'api.github.com'>
2017-06-12 00:25:41.2583|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   在 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)>
2017-06-12 00:25:41.2700|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <System>
2017-06-12 00:25:41.2700|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <System.Net.Sockets.Socket GetConnection(System.Net.PooledStream, System.Object, Boolean, System.Net.IPAddress ByRef, System.Net.Sockets.Socket ByRef, System.Net.Sockets.Socket ByRef)>
2017-06-12 00:25:41.2700|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2146233079>
2017-06-12 00:25:41.2700|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------
2017-06-12 00:25:41.3099|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2017-06-12 00:25:41.3099|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2017-06-12 00:25:41.3118|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.Net.WebException>
2017-06-12 00:25:41.3118|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <未能解析此远程名称: 'api.github.com'>
2017-06-12 00:25:41.3118|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   在 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   在 System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)>
2017-06-12 00:25:41.3118|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <System>
2017-06-12 00:25:41.3118|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <System.Net.Sockets.Socket GetConnection(System.Net.PooledStream, System.Object, Boolean, System.Net.IPAddress ByRef, System.Net.Sockets.Socket ByRef, System.Net.Sockets.Socket ByRef)>
2017-06-12 00:25:41.3118|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2146233079>
2017-06-12 00:25:41.3118|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------
2017-06-12 00:25:41.3803|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2017-06-12 00:25:41.3803|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2017-06-12 00:25:41.3803|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.Net.WebException>
2017-06-12 00:25:41.3803|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <未能解析此远程名称: 'api.github.com'>
2017-06-12 00:25:41.3965|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)>
2017-06-12 00:25:41.3965|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <System>
2017-06-12 00:25:41.3965|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <System.Net.Sockets.Socket GetConnection(System.Net.PooledStream, System.Object, Boolean, System.Net.IPAddress ByRef, System.Net.Sockets.Socket ByRef, System.Net.Sockets.Socket ByRef)>
2017-06-12 00:25:41.3965|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2146233079>
2017-06-12 00:25:41.3965|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------
2017-06-12 00:25:41.3965|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2017-06-12 00:25:41.3965|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2017-06-12 00:25:41.3965|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.Net.WebException>
2017-06-12 00:25:41.4054|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <未能解析此远程名称: 'api.github.com'>
2017-06-12 00:25:41.4054|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)>
2017-06-12 00:25:41.4054|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <System>
2017-06-12 00:25:41.4054|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <System.Net.Sockets.Socket GetConnection(System.Net.PooledStream, System.Object, Boolean, System.Net.IPAddress ByRef, System.Net.Sockets.Socket ByRef, System.Net.Sockets.Socket ByRef)>
2017-06-12 00:25:41.4054|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2146233079>
2017-06-12 00:25:41.4054|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------
2017-06-12 00:25:41.4403|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2017-06-12 00:25:41.4403|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2017-06-12 00:25:41.4403|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.Net.WebException>
2017-06-12 00:25:41.4403|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <未能解析此远程名称: 'api.github.com'>
2017-06-12 00:25:41.5191|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)>
2017-06-12 00:25:41.5191|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <System>
2017-06-12 00:25:41.5191|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <System.Net.Sockets.Socket GetConnection(System.Net.PooledStream, System.Object, Boolean, System.Net.IPAddress ByRef, System.Net.Sockets.Socket ByRef, System.Net.Sockets.Socket ByRef)>
2017-06-12 00:25:41.5191|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2146233079>
2017-06-12 00:25:41.5191|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------
2017-06-12 00:25:41.5191|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2017-06-12 00:25:41.5191|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2017-06-12 00:25:41.5191|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.Net.WebException>
2017-06-12 00:25:41.5191|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <未能解析此远程名称: 'api.github.com'>
2017-06-12 00:25:41.5681|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Wox.Infrastructure.Http.Http.<Get>d__7.MoveNext() 位置 C:\projects\wox\Wox.Infrastructure\Http\Http.cs:行号 56
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)>
2017-06-12 00:25:41.5681|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <System>
2017-06-12 00:25:41.5681|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <System.Net.Sockets.Socket GetConnection(System.Net.PooledStream, System.Object, Boolean, System.Net.IPAddress ByRef, System.Net.Sockets.Socket ByRef, System.Net.Sockets.Socket ByRef)>
2017-06-12 00:25:41.5681|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2146233079>
2017-06-12 00:25:41.5681|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------
2017-06-12 00:25:41.5681|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2017-06-12 00:25:41.5681|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2017-06-12 00:25:41.5681|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.Net.WebException>
2017-06-12 00:25:41.5681|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <未能解析此远程名称: 'api.github.com'>
2017-06-12 00:25:41.5954|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Wox.Infrastructure.Http.Http.<Get>d__7.MoveNext() 位置 C:\projects\wox\Wox.Infrastructure\Http\Http.cs:行号 56
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Wox.Core.Updater.<GitHubUpdateManager>d__3.MoveNext() 位置 C:\projects\wox\Wox.Core\Updater.cs:行号 98
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)>
2017-06-12 00:25:41.5954|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <System>
2017-06-12 00:25:41.5954|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <System.Net.Sockets.Socket GetConnection(System.Net.PooledStream, System.Object, Boolean, System.Net.IPAddress ByRef, System.Net.Sockets.Socket ByRef, System.Net.Sockets.Socket ByRef)>
2017-06-12 00:25:41.5954|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2146233079>
2017-06-12 00:25:41.5954|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------
2017-06-12 00:25:41.5954|ERROR|Updater.UpdateApp|-------------------------- Begin exception --------------------------
2017-06-12 00:25:41.5954|ERROR|Updater.UpdateApp|Please check your connection and proxy settings to api.github.com.
2017-06-12 00:25:41.5954|ERROR|Updater.UpdateApp|Exception fulle name:
 <System.Net.WebException>
2017-06-12 00:25:41.5954|ERROR|Updater.UpdateApp|Exception message:
 <未能解析此远程名称: 'api.github.com'>
2017-06-12 00:25:41.5954|ERROR|Updater.UpdateApp|Exception stack trace:
 <   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Wox.Infrastructure.Http.Http.<Get>d__7.MoveNext() 位置 C:\projects\wox\Wox.Infrastructure\Http\Http.cs:行号 56
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Wox.Core.Updater.<GitHubUpdateManager>d__3.MoveNext() 位置 C:\projects\wox\Wox.Core\Updater.cs:行号 98
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Wox.Core.Updater.<UpdateApp>d__1.MoveNext() 位置 C:\projects\wox\Wox.Core\Updater.cs:行号 30>
2017-06-12 00:25:41.6092|ERROR|Updater.UpdateApp|Exception source:
 <System>
2017-06-12 00:25:41.6092|ERROR|Updater.UpdateApp|Exception target site:
 <System.Net.Sockets.Socket GetConnection(System.Net.PooledStream, System.Object, Boolean, System.Net.IPAddress ByRef, System.Net.Sockets.Socket ByRef, System.Net.Sockets.Socket ByRef)>
2017-06-12 00:25:41.6092|ERROR|Updater.UpdateApp|Exception HResult:
 <-2146233079>
2017-06-12 00:25:41.6092|ERROR|Updater.UpdateApp|-------------------------- End exception --------------------------
2017-06-12 08:12:57.0924|INFO|App.OnStartup|Begin Wox startup ----------------------------------------------------
2017-06-12 08:12:59.1098|INFO|App.OnStartup|Runtime info:
Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.14393.0
IntPtr Length: 8
x64: True
2017-06-12 08:13:00.5029|ERROR|BinaryStorage.TryLoad|Zero length cache file <C:\Users\MichelleZhang\AppData\Roaming\Wox\Cache\Image.cache>
2017-06-12 08:13:02.6689|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2017-06-12 08:13:02.6689|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2017-06-12 08:13:02.6689|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.IO.IOException>
2017-06-12 08:13:02.6689|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <文件“C:\Users\MichelleZhang\AppData\Roaming\Wox\Cache\Image.cache”正由另一进程使用，因此该进程无法访问此文件。>
2017-06-12 08:13:04.4396|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)>
2017-06-12 08:13:04.5625|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <mscorlib>
2017-06-12 08:13:04.6157|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <Void WinIOError(Int32, System.String)>
2017-06-12 08:13:04.6157|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2147024864>
2017-06-12 08:13:04.6157|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------
2017-06-12 08:13:10.8905|FATAL|UnHandledException|
## Exception

```
System.IO.IOException: 文件“C:\Users\MichelleZhang\AppData\Roaming\Wox\Cache\Image.cache”正由另一进程使用，因此该进程无法访问此文件。
   Source: mscorlib
   TargetAssembly: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
   TargetModule: CommonLanguageRuntimeLibrary
   TargetSite: Void WinIOError(Int32, System.String)
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   在 System.IO.FileStream..ctor(String path, FileMode mode)
   在 Wox.Infrastructure.Storage.BinaryStorage`1.Save(T data) 位置 C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:行号 99
   在 Wox.Infrastructure.Storage.BinaryStorage`1.TryLoad(T defaultData) 位置 C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:行号 44
   在 Wox.Infrastructure.Image.ImageLoader.Initialize() 位置 C:\projects\wox\Wox.Infrastructure\Image\ImageLoader.cs:行号 37
   在 Wox.App.<OnStartup>b__10_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 52
   在 Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 31
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

## Environment
* Command Line: "C:\Users\MichelleZhang\AppData\Local\Wox\app-1.3.424\Wox.exe" 
* Timestamp: 06/12/2017 08:13:10
* Wox version: 1.3.424
* OS Version: Microsoft Windows NT 10.0.14393.0
* IntPtr Length: 8
* x64: True
* Python Path: 
* Everything SDK Path: 
* CLR Version: 4.0.30319.42000
* Installed .NET Framework: 
   * v2.0.50727 2.0.50727.4927 SP2
   * v3.0 3.0.30729.4926 SP2
   * v3.5 3.5.30729.4926 SP1
   * v4 Client 4.6.01586
   * v4 Full 4.6.01586
   * v4.0 Client 4.0.0.0

## Assemblies - Wox.exe

* Wox, Version=1.3.424.0, Culture=neutral, PublicKeyToken=null (C:\Users\MichelleZhang\AppData\Local\Wox\app-1.3.424\Wox.exe)
* Wox.Infrastructure, Version=1.3.424.0, Culture=neutral, PublicKeyToken=null (C:\Users\MichelleZhang\AppData\Local\Wox\app-1.3.424\Wox.Infrastructure.dll)
* Wox.Plugin, Version=1.3.424.0, Culture=neutral, PublicKeyToken=null (C:\Users\MichelleZhang\AppData\Local\Wox\app-1.3.424\Wox.Plugin.dll)
* Wox.Core, Version=1.3.424.0, Culture=neutral, PublicKeyToken=null (C:\Users\MichelleZhang\AppData\Local\Wox\app-1.3.424\Wox.Core.dll)
* NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Users\MichelleZhang\AppData\Local\Wox\app-1.3.424\NLog.dll)
* mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
* PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
* WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
* System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
* System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
* PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
* System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
* System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
* System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
* System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
* PresentationFramework.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.resources\v4.0_4.0.0.0_zh-Hans_31bf3856ad364e35\PresentationFramework.resources.dll)
* System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)
* System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
* System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
* mscorlib.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_zh-Hans_b77a5c561934e089\mscorlib.resources.dll)

2017-06-12 08:14:51.2769|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2017-06-12 08:14:51.2769|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2017-06-12 08:14:51.2769|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.Deployment.Application.InvalidDeploymentException>
2017-06-12 08:14:51.2769|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <未设置应用程序标识。>
2017-06-12 08:14:51.2769|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   在 System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()>
2017-06-12 08:14:51.2769|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <System.Deployment>
2017-06-12 08:14:51.2909|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <System.Deployment.Application.ApplicationDeployment get_CurrentDeployment()>
2017-06-12 08:14:51.2909|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2146233087>
2017-06-12 08:14:51.2909|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------
2017-06-12 08:15:35.0193|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2017-06-12 08:15:35.3034|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2017-06-12 08:15:35.3034|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.FormatException>
2017-06-12 08:15:35.3064|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <输入字符串的格式不正确。>
2017-06-12 08:15:36.5917|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   在 System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)>
2017-06-12 08:15:36.5917|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <mscorlib>
2017-06-12 08:15:36.5917|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <Double ParseDouble(System.String, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)>
2017-06-12 08:15:36.5917|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2146233033>
2017-06-12 08:15:36.5917|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------
2017-06-12 08:18:23.6976|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2017-06-12 08:18:23.6976|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2017-06-12 08:18:23.6976|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.Runtime.InteropServices.COMException>
2017-06-12 08:18:23.6976|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <OpenClipboard 失败 (异常来自 HRESULT:0x800401D0 (CLIPBRD_E_CANT_OPEN))>
2017-06-12 08:18:23.7785|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   在 System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   在 System.Windows.Clipboard.Flush()>
2017-06-12 08:18:23.7785|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <mscorlib>
2017-06-12 08:18:23.7785|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <Void ThrowExceptionForHRInternal(Int32, IntPtr)>
2017-06-12 08:18:23.7785|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2147221040>
2017-06-12 08:18:23.7785|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------
2017-06-12 08:18:24.1460|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2017-06-12 08:18:24.1460|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2017-06-12 08:18:24.1460|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.Runtime.InteropServices.COMException>
2017-06-12 08:18:24.1460|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <无效的 FORMATETC 结构 (异常来自 HRESULT:0x80040064 (DV_E_FORMATETC))>
2017-06-12 08:18:24.1630|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   在 System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   在 System.Windows.DataObject.System.Runtime.InteropServices.ComTypes.IDataObject.GetData(FORMATETC& formatetc, STGMEDIUM& medium)>
2017-06-12 08:18:24.1630|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <mscorlib>
2017-06-12 08:18:24.1660|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <Void ThrowExceptionForHRInternal(Int32, IntPtr)>
2017-06-12 08:18:24.1660|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2147221404>
2017-06-12 08:18:24.1660|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------

6. 截图 （可选）：

**Comment by lances101** [comment] 2017-12-20 12:44
Duplicate of #1394 

You can keep track of the problem in the mentioned issue.

**Closed as completed by lances101** 2017-12-20 12:44 UTC
