### ISSUE TITLE
Wox got an error

### ISSUE THREAD

**Issue by santhosh609** [Wox-launcher/Wox#1473] opened 2017-06-16 18:52 UTC
Python Path: 
Everything SDK Path: 
Date: 06/16/2017 22:49:21
Exception:
mscorlib
System.IO.IOException
The process cannot access the file 'C:\Users\santh\AppData\Roaming\Wox\Cache\Pinyin.cache' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Wox.Infrastructure.Storage.BinaryStorage`1.Save(T data) in C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:line 99
   at Wox.Infrastructure.Storage.BinaryStorage`1.TryLoad(T defaultData) in C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:line 44
   at Wox.Infrastructure.Alphabet.<>c.<Initialize>b__3_0() in C:\projects\wox\Wox.Infrastructure\Alphabet.cs:line 25
   at Wox.Infrastructure.Stopwatch.Normal(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 31
   at Wox.Infrastructure.Alphabet.Initialize() in C:\projects\wox\Wox.Infrastructure\Alphabet.cs:line 29
   at Wox.App.<OnStartup>b__10_0() in C:\projects\wox\Wox\App.xaml.cs:line 54
   at Wox.Infrastructure.Stopwatch.Normal(String message, Action action) in C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:line 31
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2017-06-16.txt](https://github.com/Wox-launcher/Wox/files/1081683/2017-06-16.txt)

**Comment by lances101** [comment] 2017-12-26 23:52
Duplicate of #1394

**Closed as completed by lances101** 2017-12-26 23:52 UTC
