### ISSUE TITLE
一个异常反馈

### ISSUE THREAD

**Issue by l1987i** [Wox-launcher/Wox#1626] opened 2017-10-13 00:53 UTC
2017-10-13 08:50:22.3128|INFO|App.OnStartup|Begin Wox startup ----------------------------------------------------
2017-10-13 08:50:22.4902|INFO|App.OnStartup|Runtime info:
Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.10586.0
IntPtr Length: 8
x64: True
2017-10-13 08:50:22.4983|ERROR|BinaryStorage.TryLoad|Zero length cache file <C:\Users\3046\AppData\Roaming\Wox\Cache\Image.cache>
2017-10-13 08:50:22.5314|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2017-10-13 08:50:22.5314|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2017-10-13 08:50:22.5314|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.IO.IOException>
2017-10-13 08:50:22.5314|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <文件“C:\Users\3046\AppData\Roaming\Wox\Cache\Image.cache”正由另一进程使用，因此该进程无法访问此文件。>
2017-10-13 08:50:22.5554|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)>
2017-10-13 08:50:22.5554|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <mscorlib>
2017-10-13 08:50:22.5554|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <Void WinIOError(Int32, System.String)>
2017-10-13 08:50:22.5554|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2147024864>
2017-10-13 08:50:22.5554|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------
2017-10-13 08:50:23.4067|FATAL|UnHandledException|
## Exception

```
System.IO.IOException: 文件“C:\Users\3046\AppData\Roaming\Wox\Cache\Image.cache”正由另一进程使用，因此该进程无法访问此文件。
   Source: mscorlib
   TargetAssembly: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
   TargetModule: CommonLanguageRuntimeLibrary
   TargetSite: Void WinIOError(Int32, System.String)
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   在 System.IO.FileStream..ctor(String path, FileMode mode)
   在 Wox.Infrastructure.Storage.BinaryStorage`1.Save(T data) 位置 C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:行号 99
   在 Wox.Infrastructure.Storage.BinaryStorage`1.TryLoad(T defaultData) 位置 C:\projects\wox\Wox.Infrastructure\Storage\BinaryStorage.cs:行号 44
   在 Wox.Infrastructure.Image.ImageLoader.Initialize() 位置 C:\projects\wox\Wox.Infrastructure\Image\ImageLoader.cs:行号 37
   在 Wox.App.<OnStartup>b__10_0() 位置 C:\projects\wox\Wox\App.xaml.cs:行号 52
   在 Wox.Infrastructure.Stopwatch.Normal(String message, Action action) 位置 C:\projects\wox\Wox.Infrastructure\Stopwatch.cs:行号 31
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

## Environment
* Command Line: "C:\Users\3046\AppData\Local\Wox\app-1.3.424\Wox.exe" --squirrel-firstrun
* Timestamp: 10/13/2017 08:50:23
* Wox version: 1.3.424
* OS Version: Microsoft Windows NT 10.0.10586.0
* IntPtr Length: 8
* x64: True
* Python Path: 
* Everything SDK Path: 
* CLR Version: 4.0.30319.42000
* Installed .NET Framework: 
   * v2.0.50727 2.0.50727.4927 SP2
   * v3.0 3.0.30729.4926 SP2
   * v3.5 3.5.30729.4926 SP1
   * v4 Client 4.6.01590
   * v4 Full 4.6.01590
   * v4.0 Client 4.0.0.0

## Assemblies - Wox.exe

* Wox, Version=1.3.424.0, Culture=neutral, PublicKeyToken=null (C:\Users\3046\AppData\Local\Wox\app-1.3.424\Wox.exe)
* Wox.Infrastructure, Version=1.3.424.0, Culture=neutral, PublicKeyToken=null (C:\Users\3046\AppData\Local\Wox\app-1.3.424\Wox.Infrastructure.dll)
* Wox.Plugin, Version=1.3.424.0, Culture=neutral, PublicKeyToken=null (C:\Users\3046\AppData\Local\Wox\app-1.3.424\Wox.Plugin.dll)
* Wox.Core, Version=1.3.424.0, Culture=neutral, PublicKeyToken=null (C:\Users\3046\AppData\Local\Wox\app-1.3.424\Wox.Core.dll)
* NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Users\3046\AppData\Local\Wox\app-1.3.424\NLog.dll)
* mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
* PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
* WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
* System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
* System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
* PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
* System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
* System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
* System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
* System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
* PresentationFramework.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=31bf3856ad364e35 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.resources\v4.0_4.0.0.0_zh-Hans_31bf3856ad364e35\PresentationFramework.resources.dll)
* System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)
* System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
* System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
* mscorlib.resources, Version=4.0.0.0, Culture=zh-Hans, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_zh-Hans_b77a5c561934e089\mscorlib.resources.dll)

2017-10-13 08:50:57.6023|ERROR|App.RegisterAppDomainExceptions|-------------------------- Begin exception --------------------------
2017-10-13 08:50:57.6023|ERROR|App.RegisterAppDomainExceptions|First Chance Exception:
2017-10-13 08:50:57.6023|ERROR|App.RegisterAppDomainExceptions|Exception fulle name:
 <System.Deployment.Application.InvalidDeploymentException>
2017-10-13 08:50:57.6023|ERROR|App.RegisterAppDomainExceptions|Exception message:
 <未设置应用程序标识。>
2017-10-13 08:50:57.6263|ERROR|App.RegisterAppDomainExceptions|Exception stack trace:
 <   在 System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()>
2017-10-13 08:50:57.6263|ERROR|App.RegisterAppDomainExceptions|Exception source:
 <System.Deployment>
2017-10-13 08:50:57.6263|ERROR|App.RegisterAppDomainExceptions|Exception target site:
 <System.Deployment.Application.ApplicationDeployment get_CurrentDeployment()>
2017-10-13 08:50:57.6263|ERROR|App.RegisterAppDomainExceptions|Exception HResult:
 <-2146233087>
2017-10-13 08:50:57.6263|ERROR|App.RegisterAppDomainExceptions|-------------------------- End exception --------------------------

**Comment by jhdxr** [comment] 2017-10-16 13:41
duplicate of #1394

**Closed as completed** 2017-12-20 12:51 UTC
