### ISSUE TITLE
报错？

### ISSUE THREAD

**Issue by celia0512** [Wox-launcher/Wox#1557] opened 2017-08-12 11:34 UTC
Wox version: 1.3.424
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
IntPtr Length: 4
x64: False

Python Path: 
Everything SDK Path: 
Date: 08/12/2017 19:11:54
Exception:
Wox.Core
System.NullReferenceException
未将对象引用设置到对象的实例。
   在 Wox.Core.Resource.Internationalization.ChangeLanguage(Language language) 位置 C:\projects\wox\Wox.Core\Resource\Internationalization.cs:行号 89
   在 Wox.SettingWindow.OnLanguageChanged(Object sender, SelectionChangedEventArgs e) 位置 C:\projects\wox\Wox\SettingWindow.xaml.cs:行号 46
   在 System.Windows.Controls.SelectionChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   在 System.Windows.Controls.ComboBox.OnSelectionChanged(SelectionChangedEventArgs e)
   在 System.Windows.Controls.Primitives.Selector.InvokeSelectionChanged(List`1 unselectedInfos, List`1 selectedInfos)
   在 System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   在 System.Windows.Controls.Primitives.Selector.SelectionChanger.SelectJustThisItem(ItemInfo info, Boolean assumeInItemsCollection)
   在 System.Windows.Controls.Primitives.Selector.SelectItemWithValue(Object value)
   在 System.Windows.Controls.Primitives.Selector.CoerceSelectedValue(DependencyObject d, Object value)
   在 System.Windows.DependencyObject.ProcessCoerceValue(DependencyProperty dp, PropertyMetadata metadata, EntryIndex& entryIndex, Int32& targetIndex, EffectiveValueEntry& newEntry, EffectiveValueEntry& oldEntry, Object& oldValue, Object baseValue, Object controlValue, CoerceValueCallback coerceValueCallback, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, Boolean skipBaseValueChecks)
   在 System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   在 System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   在 System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   在 System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   在 System.Windows.Data.BindingExpression.Activate(Object item)
   在 System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   在 System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   在 MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   在 MS.Internal.Data.DataBindEngine.Run(Object arg)
   在 MS.Internal.Data.DataBindEngine.OnLayoutUpdated(Object sender, EventArgs e)
   在 System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   在 System.Windows.ContextLayoutManager.UpdateLayout()
   在 System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   在 System.Windows.Media.MediaContext.InvokeOnRenderCallback.DoWork()
   在 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   在 System.Windows.Interop.HwndTarget.OnResize()
   在 System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   在 System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by lances101** [comment] 2017-12-20 12:20
Duplicate of https://github.com/Wox-launcher/Wox/issues/1356
If possible, indicate the language before clicking, the language you were choosing and post an error log file.

**Closed as completed by lances101** 2017-12-20 12:20 UTC
