### ISSUE TITLE
"File is in use by Wox"

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [Wox-launcher/Wox#1706] opened 2017-11-26 06:47 UTC
A lot of the times I use Wox, is to find a file that I want to delete. This is made difficult by how this message appears after getting into the folder and trying to delete said file. 

Is there any way to quickly clear the cache?

**Comment by lances101** [comment] 2017-12-22 16:15
Duplicate of #1394

**Closed as completed by lances101** 2017-12-22 16:15 UTC
