### ISSUE TITLE
report bug

### ISSUE THREAD

**Issue by ChennJoe** [Wox-launcher/Wox#1851] opened 2018-01-21 02:57 UTC
[

### Are you submitting a bug report?

(write your answer here)

### Steps to reproduce

1.
2.
3.

### Wox Error Window text

(paste here)

### Detailed logs

(drop your log file here)

### Screenshots (optional)

(drop your screenshot here)

**Comment by lances101** [comment] 2018-01-21 18:11
Duplicate of #1789

**Closed as completed by lances101** 2018-01-21 18:11 UTC
