### ISSUE TITLE
在输入框删除前面输入的字符的时候，突然报错

### ISSUE THREAD

**Issue by Ramon403** [Wox-launcher/Wox#1556] opened 2017-08-11 09:34 UTC
[错误日志.TXT](https://github.com/Wox-launcher/Wox/files/1217447/default.TXT)

Wox version: 1.3.424
OS Version: Microsoft Windows NT 10.0.15063.0
IntPtr Length: 8
x64: True

Python Path: C:\Python27\pythonw.exe
Everything SDK Path: C:\Users\Ramon\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 08/11/2017 17:30:11
Exception:

mscorlib
System.ArgumentOutOfRangeException
索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.Collections.ArrayList.set_Item(Int32 index, Object value)
   在 System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   在 System.Windows.Data.CollectionView.ProcessChangeLog(ArrayList changeLog, Boolean processAll)
   在 System.Windows.Data.CollectionView.ProcessInvoke(Object arg)
   在 MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by lances101** [comment] 2017-12-26 22:19
Duplicate of #1404 
Please track this problem there.

**Closed as completed by lances101** 2017-12-26 22:19 UTC
